version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
    cooldown:
      default-days: 7
    labels:
      - "dependabot"
    assignees:
      - sato-toma

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
    labels:
      - "dependabot"
    assignees:
      - sato-toma
